apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
  labels:
    app: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
        - name: mysql-order
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: order_service
            - name: MYSQL_USER
              value: ibatulanand
            - name: MYSQL_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-order-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: mysql-order-data
          emptyDir: {}