apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest

          command: ["/opt/keycloak/bin/kc.sh"]
          args:
            - start-dev
            - --import-realm
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          env:
            - name: DB_VENDOR
              value: MYSQL
            - name: DB_ADDR
              value: keycloak-mysql
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: password
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: keycloak-realm-data
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: keycloak-realm-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
