apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8080']
      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8080']
      - job_name: 'inventory-service'
        static_configs:
          - targets: ['inventory-service:8080']
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8080']
