apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  template:
    metadata:
      labels:
        app: mysql-order
    spec:
      containers:
        - name: mysql-order
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: order_service
            - name: MYSQL_USER
              value: ibatulanand
            - name: MYSQL_PASSWORD
              value: password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - name: mysql-order-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-order-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order
spec:
  selector:
    app: mysql-order
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
