name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'silicon-airlock-456802-p4'
  GAR_LOCATION: 'asia-southeast1'
  GKE_CLUSTER: 'ecommerce'
  GKE_ZONE: 'asia-southeast1'
  DEPLOYMENT_NAME: 'gke-test'
  REPOSITORY: 'samples'
  IMAGE: 'static-site'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Authenticate với GCP bằng JSON key
      - name: 'Authenticate to GCP with Service Account'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # 3. Lấy kubeconfig của GKE
      - name: 'Get GKE credentials'
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
            --region ${{ env.GKE_ZONE }}

      # 4. Build & push image
      - name: 'Build and push Docker image'
        run: |
          IMAGE_URI="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA::8}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # 5. Deploy lên GKE
      - name: 'Deploy to GKE'
        run: |
          sed -i "s|image: .*|image: $IMAGE_URI|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
