name: Deploy to GKE with Public Images

on:
  push:
    branches:
      - main # Trigger on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate to GCP with Service Account
      - name: Authenticate to GCP with Service Account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Setup Google Cloud SDK
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'silicon-airlock-456802-p4'

      # Connect to GKE Cluster
      - name: Connect to GKE Cluster
        run: |
          gcloud container clusters get-credentials ecommerce --region asia-southeast1


      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet || true

      # Authenticate Docker with Google Cloud
      - name: Authenticate Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      # Build and push the Docker images for all services
      - name: Build and Push Docker Images
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          # Build images for each service
          docker build --no-cache --build-arg=SERVICE_NAME=api-gateway --tag=asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/api-gateway:latest .
          docker build --no-cache --build-arg=SERVICE_NAME=discovery-server --tag=asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/discovery-server:latest .
          docker build --no-cache --build-arg=SERVICE_NAME=product-service --tag=asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/product-service:latest .
          docker build --no-cache --build-arg=SERVICE_NAME=order-service --tag=asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/order-service:latest .
          docker build --no-cache --build-arg=SERVICE_NAME=inventory-service --tag=asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/inventory-service:latest .
          docker build --no-cache --build-arg=SERVICE_NAME=notification-service --tag=asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/notification-service:latest .

          # Push images to Google Container Registry
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/api-gateway:latest
          docker push asia-southeast1-d
