name: 'Deploy to GKE with Public Images'

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to GCP with Service Account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'silicon-airlock-456802-p4'

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ecommerce --region asia-southeast1

      - name: Deploy manifests to GKE
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/api-gateway || true
          kubectl rollout status deployment/discovery-server || true
          kubectl rollout status deployment/product-service || true
          kubectl rollout status deployment/order-service || true
          kubectl rollout status deployment/inventory-service || true
          kubectl rollout status deployment/notification-service || true
